### ISSUE TITLE
Clear Canvas is not transmitted on socket

### ISSUE THREAD

**Issue by NeenuAVarghese** [NeenuAVarghese/guesswhat#7]

**Comment by NeenuAVarghese** [comment]
functionality implemented in latest commit

**Comment by NeenuAVarghese** [comment]
Problem with this feature with the changed behaviour

**Comment by NeenuAVarghese** [comment]
Handled the issue.

**Comment by mittman** [comment]
This is broken again

**Comment by NeenuAVarghese** [comment]
Handled this issue in latest commit. Please test
